; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[kalvi][download][type] = ""
projects[kalvi][download][url] = ""
projects[kalvi][type] = "profile"

; Modules
projects[ctools][version] = "1.3"

projects[chosen][version] = "2.0-alpha4"

projects[devel][version] = "1.3"

projects[eck][version] = "2.0-rc2"

projects[entity][version] = "1.3"

projects[entityreference][version] = "1.1"

projects[features][version] = "2.0"

projects[media][version] = "1.4"

projects[h5p][version] = "1.0-alpha1"

projects[inline_comments][version] = "1.0-beta2"

projects[jquery_update][version] = "2.3"

projects[libraries][version] = "2.0"

projects[link][version] = "1.2"

projects[oembed][version] = "0.1-beta3"

projects[media_youtube][version] = "2.0-rc4"

projects[relation][version] = "1.0-rc4"

projects[relation_select][version] = "1.x-dev"

projects[reply][version] = "1.x-dev"

projects[subform][version] = "1.0-alpha2"

projects[views][version] = "3.7"

; Themes
projects[bootstrap][version] = "3.0"

projects[omega][version] = "4.2"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[coding_problem][download][type] = ""
;projects[coding_problem][download][url] = ""
;projects[coding_problem][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[ideone][download][type] = ""
;projects[ideone][download][url] = ""
;projects[ideone][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[sessions][download][type] = ""
;projects[sessions][download][url] = ""
;projects[sessions][type] = "module"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;libraries[chosen][download][type] = ""
;libraries[chosen][download][url] = ""
;libraries[chosen][directory_name] = "chosen"
;libraries[chosen][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;libraries[codemirror][download][type] = ""
;libraries[codemirror][download][url] = ""
;libraries[codemirror][directory_name] = "codemirror"
;libraries[codemirror][type] = "library"

